### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by vladislavaSim**
Added API, bundler and some new features ( e.g. new method, new error checking and default parameter in daysInMonth)

### CODE REVIEW

**Review by serhiihiba — CHANGES_REQUESTED** [review]
Rewrite it to use modules, please like `import { Something } from "../../something"` and change name of bundle file from `capycalendar-bundle.js` to `capycalendar.js`

**Comment by serhiihiba** [comment]
@vladislavaSim  also, please, use GitHub Actions to automatically setup your tests, so we can always see if everything is fine before review

**Comment by vladislavaSim** [comment]
> Rewrite it to use modules, please like `import { Something } from "../../something"` and change name of bundle file from `capycalendar-bundle.js` to `capycalendar.js`

@serhiijun import statement is only supported in ECMAScript modules (ES modules) and cannot be used in a CommonJS module, which is the default module system in Node.js.

Seems like I need the .mjs extension (indicates that it's an ES module) and run `node --experimental-modules app.js` in terminal. Is it correct?

**Comment by serhiihiba** [comment]
@vladislavaSim No, that's mostly for ssr or server services etc, so let's just use "type": module" in package.json I think it should works without commonjs haha
But I'm not sure🙃

**Pull request merged**
